M48
; DRILL file {KiCad 8.0.1} date 2024-05-04T10:24:33-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-04T10:24:33-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.06Y-3.4768
X5.06Y-3.7043
T2
X4.935Y-3.878
X4.935Y-4.1457
M30
